import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from 'next/image'


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body className="bg-zinc-950 text-white overflow-hidden"               style={{ backgroundImage: 'url("/images/hero-bg.png")' }}
      >
        <div className="flex h-screen overflow-hidden">
  {/* 左側：固定背景とコピー */}
  <div className="w-1/2 h-screen relative text-white">
    <div className="absolute inset-0 flex flex-col items-center justify-center text-center px-6 z-10 space-y-6">
      <h1 className="text-5xl font-serif tracking-wide">Seen</h1>
      <hr className="w-32 border-t border-slate-300" />
      <p className="text-lg leading-loose">
        Seenは、感情を投稿できる。<br />
        だけど誰にも見られない。<br />
        そんな“SNS風”アプリです。
      </p>
    </div>
  </div>

  {/* 右側：スクロールUI */}
  <div className="w-1/2 h-screen flex items-center justify-center relative">
    <div className="w-[375px] h-[667px] bg-[#0e2a3a] rounded-[32px] shadow-xl p-4">
      {/* 仮のカード枠：ここにメイン画面コンポーネントを追加 */}
    </div>

    {/* ハンバーガーメニュー */}
    <button className="absolute top-6 right-6 space-y-1 z-20">
      <div className="w-6 h-0.5 bg-white" />
      <div className="w-6 h-0.5 bg-white" />
      <div className="w-6 h-0.5 bg-white" />
    </button>
  </div>
</div>

      </body>
    </html>
  )
}

